stzn/the-swift-programming-language-jp

- language-guide/the-basics.md
タイポを修正してみましたーー
また、L273行 $10^{2}$ あたりの LaTeX がレンダリングされていません。
> Fix typo in the-basics

- language-guide/error-handling.md
はじめまして。The Swift Programming Language(日本語版)、ありがたく読ませていただいております。エラー処理の一部で typo を見つけましたので修正 PR をさせていただきました。
> Fix typos error-handling.md

- language-reference/about-the-language-reference.md
> [About the Language Reference]文言の修正

- language-reference/lexical-structure.md
- language-reference/summary-of-the-grammar.md
> [Lexical Structure]文言の修正

- language-reference/attributes.md
> [Attributes]文言の修正

- language-reference/patterns.md
- revision-history/document-revision-history.md
> [Patterns]文言の修正

- language-reference/expressions.md
- language-reference/summary-of-the-grammar.md
> [Summary of the Grammar]文言の修正

- language-guide/strings-and-characters.md
> [Strings and Characters]リンクの修正

- language-guide/the-basics.md
> [The Basics]リンクの修正

- language-guide/basic-operators.md
> [Basic Operators]リンクの修正

- language-guide/basic-operators.md
- language-guide/strings-and-characters.md
- language-guide/the-basics.md
> target=_selfを追加

- language-guide/collection-types.md
- language-guide/control-flow.md
- language-guide/functions.md
> [Collection Types, Control Flow, Functions]リンクの修正

- language-reference/lexical-structure.md
- language-reference/types.md
> [Lexical Structure, Types]リンクの修正

- language-reference/expressions.md
- language-reference/statements.md
> [Expressions, Statements]リンクの修正

- language-reference/declarations.md
> test link id

- language-reference/declarations.md
This reverts commit df411e779cf55c86a8ad31272ac1f30702baf55c.
> Revert "test link id"

- language-guide/access-control.md
https://github.com/stzn/the-swift-programming-language-jp/issues/184
> [アクセスコントロール]日本語⇄英語タイトル

- .github/pull_request_template.md
> PR用テンプレート作成

- language-guide/the-basics.md
> [基本]オプショナルバインディング if let構文の説明を追加

- language-guide/control-flow.md
> [制御フロー]APIアベイラビリティチェック guard文での#availableの使用方法の追加、#unavailableの追加

- .github/workflows/ci.yml
- README.md
Reverts stzn/the-swift-programming-language-jp#259
> Revert "[README]Contributorsの追加"

- .github/workflows/ci.yml
- README.md
> [README]Contributorsの追加

- README.md
This reverts commit a4ae89bccceffbe683be2a2156cfa3847de1ebd1.
> Revert "remove GitBook Bot"

- README.md
> [README]貢献者の追加

- .github/workflows/ci.yml
- README.md
> [README] update contributors automatically

- .github/workflows/ci.yml
- README.md
Reverts stzn/the-swift-programming-language-jp#274
> Revert "[README] update contributors automatically"

- .github/workflows/ci.yml
- README.md
> [README]update contributors automatically

- README.md
> [README] divタグ追加

- README.md
> [README] 幅の調整(テスト)

- README.md
- readme.css
> [README]table幅の調整(css導入)

- readme.css
> [README]css修正

- language-guide/access-control.md
Closes #288 
OSS初めてなので何か間違っていたら教えて頂けると助かります....
> [アクセスコントロール]原文へのリンク修正

- .github/workflows/action.yml
> pull_request_targetへの変更

- CONTRIBUTION.md
> [CONTRIBUTION]スペースの修正

- CONTRIBUTION.md
> [CONTRIBUTION]Discordチャンネルのリンクを追加

- README.md
> 英和対応表にsubscript/サブスクリプトの追加

- language-guide/access-control.md
- language-guide/advanced-operators.md
- language-guide/collection-types.md
- language-reference/declarations.md
- language-reference/expressions.md
- language-reference/statements.md
以下の機械的変更で壊れていた？箇所の修正です。
https://github.com/stzn/the-swift-programming-language-jp/commit/3baeb2db1ba1aa4cc59c36b58c7c36da98f74e2f#diff-3335217a8d3f6bcdfc72a6a999a979238bc01e18f3f17b3e28ca4b0567b2ce5dR24
> ヘッダがリンクになっている箇所を削除

- language-guide/opaque-types.md
> [Opaque Types] 原文リンクの修正

- .textlintrc
> ですます調ルールをstrict:falseに変更

- language-reference/statements.md
このPRに合わせた修正です。
https://github.com/apple/swift-book/pull/32
> [文]不要な文言の削除

- language-reference/lexical-structure.md
Closes #n<紐付けたいIssueの番号>
https://github.com/apple/swift-book/issues/37
> [単語と句読点]awaitキーワードの追加

- language-guide/concurrency.md
> [同時並行処理]非同期関数の定義と呼び出しに追加されていた文言を追加 + コード内の英単語を日本語へ変換

- language-guide/closures.md
- language-guide/collection-types.md
- language-guide/generics.md
- language-guide/initialization.md
- language-guide/opaque-types.md
- language-guide/optional-chaining.md
- language-guide/properties.md
- language-guide/type-casting.md
- welcome-to-swift/a-swift-tour.md
> 空の配列と辞書の初期化のシンタックスの変更

- language-guide/concurrency.md
> NonSendableの記述を追加

- welcome-to-swift/a-swift-tour.md
> [Swiftツアー]原文から消えているNOTEを削除

- welcome-to-swift/a-swift-tour.md
> [a-swift-tour] Concurrencyを追加

- language-guide/closures.md
- language-guide/macros.md
> 既存プロジェクトへのマクロの追加方法の修正、足りないimport文を追加

- language-guide/basic-operators.md
- language-guide/structures-and-classes.md
> 恒等作用素->同値演算子

- language-guide/concurrency.md
> [Concurrency] 全般的な内容の更新

- language-reference/declarations.md
- language-reference/types.md
>  [Declaration, Types]borrowingとconsumingの追加

- language-guide/concurrency.md
> [Concurrency]Resultのexampleの修正

- language-reference/expressions.md
- language-reference/summary-of-the-grammar.md
> [Expressions]不要なgrammerの削除

- language-guide/concurrency.md
> [Concurrency]間違っているサンプルのクラス名を修正

- language-reference/lexical-structure.md
> [字句構造]#unavailableを追加

- language-reference/attributes.md
- language-reference/statements.md
- language-reference/summary-of-the-grammar.md
> [Statements]visionOSApplicationExtension追加

- language-guide/concurrency.md
> [Concurrency]Task.addTaskUnlessCancelledの説明追記

- language-guide/concurrency.md
> [Concurrency]Task.addTaskUnlessCancelledのsample修正追加

- package.json
This reverts commit 3e7ae1a308ac2f64f36a4a251db6b6b3189629f7, reversing changes made to f8c4c20b98b40bb48c2c8b5550cb9db630e3ba78.
> Revert "Merge pull request #547 from stzn/stzn-patch-1"

- language-guide/error-handling.md
修正前：スローするの値
修正後：スローする値
Closes #556
> [error-handling] fix typo

- language-reference/attributes.md
> [属性]preconcurrencyの追加

- language-reference/lexical-structure.md
> [字句構造]borrowingとconsumingを追加

- .github/workflows/ci.yml
> contributors-readme-actionのバージョン更新

- language-reference/declarations.md
> [宣言]extensionに関するアクセス制御の記述を修正

- SUMMARY.md
- language-guide/access-control.md
- language-guide/properties.md
- language-reference/declarations.md
- revision-history/document-revision-history.md
> インデントの修正とアクセス制御の表記揺れの修正

- welcome-to-swift/a-swift-tour.md
> [A Swift Tour] typo sett -> set

- language-guide/concurrency.md
> [Concurrency]Exampleの修正

- language-reference/lexical-structure.md
> nonisolatedを追加

- language-guide/concurrency.md
- language-guide/generics.md
- language-guide/protocols.md
- language-reference/declarations.md
> [Concurrency, Generics, Protocols, Declarations]暗黙のプロトコル準拠、~Copyableなどの記述追加
